name: Create Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%s')"

      - name: Create release branch and bump version
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release${REF:10}-${{ steps.date.outputs.date }}
          git config --local user.email "ci@thatsoundboard.com"
          git config --local user.name "ThatSoundboard CI"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:11}',/" config/app.php
          git add config/app.php
          git commit -m "bump version for release"
          git push

      - name: Build assets
        run: |
          yarn install
          yarn run build

      - name: Create release archive
        run: |
          rm -rf node_modules/ test/ phpunit.xml
          tar -czf thatsoundboard.tar.gz * .env.example

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract changelog
        id: extract_changelog
        env:
          REF: ${{ github.ref }}
        run: |
          cat CHANGELOG.md > ./RELEASE_CHANGELOG

      - name: Create checksum and add to changelog
        run: |
          SUM=`sha256sum thatsoundboard.tar.gz`
          echo -e "\n#### SHA256 Checksum\n\n\`\`\`\n$SUM\n\`\`\`\n" >> ./RELEASE_CHANGELOG
          echo $SUM > checksum.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${REF:11}
          release_name: ${REF:11}
          body_path: ./RELEASE_CHANGELOG
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}

      - name: Upload binary
        id: upload-release-archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: thatsoundboard.tar.gz
          asset_name: thatsoundboard.tar.gz
          asset_content_type: application/gzip

      - name: Upload checksum
        id: upload-release-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./checksum.txt
          asset_name: checksum.txt
          asset_content_type: text/plain